In [1]:
import torch
from torch import nn, Tensor
import torch.nn.functional as F

from torch.utils.data import Dataset, DataLoader
import transformers
from transformers import BertTokenizer, BertModel, BertConfig, EncoderDecoderModel, BertForMaskedLM

from tqdm import tqdm
import os

In [2]:
print(torch.cuda.is_available())
device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)

True
cuda


In [3]:
print(bert2bert)

NameError: name 'bert2bert' is not defined

In [3]:
# bert2bert
bert2bert = EncoderDecoderModel.from_encoder_decoder_pretrained("bert-base-uncased", "bert-base-uncased")
BertLMHeadModel_new_initialized_weights = ['bert.encoder.layer.11.crossattention.self.value.bias', 'bert.encoder.layer.0.crossattention.self.key.weight', 'bert.encoder.layer.9.crossattention.output.dense.bias', 'bert.encoder.layer.5.crossattention.output.dense.weight', 'bert.encoder.layer.6.crossattention.self.key.bias', 'bert.encoder.layer.1.crossattention.self.query.weight', 'bert.encoder.layer.3.crossattention.self.value.bias', 'bert.encoder.layer.5.crossattention.self.value.bias', 'bert.encoder.layer.10.crossattention.output.dense.bias', 'bert.encoder.layer.6.crossattention.self.value.weight', 'bert.encoder.layer.3.crossattention.self.key.bias', 'bert.encoder.layer.9.crossattention.output.dense.weight', 'bert.encoder.layer.6.crossattention.self.query.bias', 'bert.encoder.layer.0.crossattention.output.dense.bias', 'bert.encoder.layer.8.crossattention.output.LayerNorm.bias', 'bert.encoder.layer.3.crossattention.output.dense.weight', 'bert.encoder.layer.2.crossattention.self.value.bias', 'bert.encoder.layer.9.crossattention.self.value.weight', 'bert.encoder.layer.2.crossattention.self.query.weight', 'bert.encoder.layer.9.crossattention.self.query.bias', 'bert.encoder.layer.9.crossattention.self.key.weight', 'bert.encoder.layer.6.crossattention.self.value.bias', 'bert.encoder.layer.9.crossattention.self.query.weight', 'bert.encoder.layer.11.crossattention.output.LayerNorm.bias', 'bert.encoder.layer.4.crossattention.output.LayerNorm.bias', 'bert.encoder.layer.7.crossattention.self.key.weight', 'bert.encoder.layer.4.crossattention.self.key.weight', 'bert.encoder.layer.7.crossattention.output.dense.bias', 'bert.encoder.layer.7.crossattention.self.value.weight', 'bert.encoder.layer.7.crossattention.output.LayerNorm.weight', 'bert.encoder.layer.9.crossattention.self.key.bias', 'bert.encoder.layer.8.crossattention.self.value.weight', 'bert.encoder.layer.3.crossattention.self.query.weight', 'bert.encoder.layer.2.crossattention.output.dense.bias', 'bert.encoder.layer.10.crossattention.self.key.bias', 'bert.encoder.layer.5.crossattention.self.key.weight', 'bert.encoder.layer.1.crossattention.output.dense.bias', 'bert.encoder.layer.4.crossattention.self.value.bias', 'bert.encoder.layer.0.crossattention.self.query.bias', 'bert.encoder.layer.0.crossattention.self.value.bias', 'bert.encoder.layer.3.crossattention.output.dense.bias', 'bert.encoder.layer.5.crossattention.self.query.weight', 'bert.encoder.layer.6.crossattention.self.key.weight', 'bert.encoder.layer.1.crossattention.self.key.weight', 'bert.encoder.layer.7.crossattention.self.key.bias', 'bert.encoder.layer.3.crossattention.self.query.bias', 'bert.encoder.layer.2.crossattention.self.value.weight', 'bert.encoder.layer.4.crossattention.self.value.weight', 'bert.encoder.layer.1.crossattention.self.query.bias', 'bert.encoder.layer.0.crossattention.self.value.weight', 'bert.encoder.layer.4.crossattention.self.key.bias', 'bert.encoder.layer.1.crossattention.output.LayerNorm.bias', 'bert.encoder.layer.7.crossattention.output.LayerNorm.bias', 'bert.encoder.layer.3.crossattention.self.value.weight', 'bert.encoder.layer.2.crossattention.self.key.bias', 'bert.encoder.layer.10.crossattention.output.LayerNorm.weight', 'bert.encoder.layer.2.crossattention.output.dense.weight', 'bert.encoder.layer.2.crossattention.self.query.bias', 'bert.encoder.layer.9.crossattention.output.LayerNorm.weight', 'bert.encoder.layer.2.crossattention.self.key.weight', 'bert.encoder.layer.10.crossattention.self.query.bias', 'bert.encoder.layer.3.crossattention.output.LayerNorm.bias', 'bert.encoder.layer.8.crossattention.self.value.bias', 'bert.encoder.layer.11.crossattention.self.value.weight', 'bert.encoder.layer.0.crossattention.output.dense.weight', 'bert.encoder.layer.6.crossattention.output.dense.weight', 'bert.encoder.layer.2.crossattention.output.LayerNorm.weight', 'bert.encoder.layer.0.crossattention.self.key.bias', 'bert.encoder.layer.0.crossattention.output.LayerNorm.weight', 'bert.encoder.layer.6.crossattention.output.dense.bias', 'bert.encoder.layer.7.crossattention.self.value.bias', 'bert.encoder.layer.8.crossattention.self.query.weight', 'bert.encoder.layer.10.crossattention.self.value.bias', 'bert.encoder.layer.2.crossattention.output.LayerNorm.bias', 'bert.encoder.layer.5.crossattention.output.dense.bias', 'bert.encoder.layer.6.crossattention.output.LayerNorm.bias', 'bert.encoder.layer.10.crossattention.self.key.weight', 'bert.encoder.layer.4.crossattention.self.query.bias', 'bert.encoder.layer.4.crossattention.output.dense.weight', 'bert.encoder.layer.11.crossattention.self.key.weight', 'bert.encoder.layer.9.crossattention.output.LayerNorm.bias', 'bert.encoder.layer.11.crossattention.self.query.weight', 'bert.encoder.layer.11.crossattention.self.key.bias', 'bert.encoder.layer.7.crossattention.output.dense.weight', 'bert.encoder.layer.4.crossattention.output.LayerNorm.weight', 'bert.encoder.layer.1.crossattention.self.value.bias', 'bert.encoder.layer.8.crossattention.self.key.bias', 'bert.encoder.layer.0.crossattention.self.query.weight', 'bert.encoder.layer.1.crossattention.self.key.bias', 'bert.encoder.layer.10.crossattention.self.value.weight', 'bert.encoder.layer.5.crossattention.self.key.bias', 'bert.encoder.layer.8.crossattention.output.dense.bias', 'bert.encoder.layer.3.crossattention.output.LayerNorm.weight', 'bert.encoder.layer.4.crossattention.self.query.weight', 'bert.encoder.layer.11.crossattention.self.query.bias', 'bert.encoder.layer.10.crossattention.output.dense.weight', 'bert.encoder.layer.6.crossattention.self.query.weight', 'bert.encoder.layer.4.crossattention.output.dense.bias', 'bert.encoder.layer.3.crossattention.self.key.weight', 'bert.encoder.layer.9.crossattention.self.value.bias', 'bert.encoder.layer.5.crossattention.self.value.weight', 'bert.encoder.layer.0.crossattention.output.LayerNorm.bias', 'bert.encoder.layer.8.crossattention.self.key.weight', 'bert.encoder.layer.1.crossattention.output.LayerNorm.weight', 'bert.encoder.layer.11.crossattention.output.dense.bias', 'bert.encoder.layer.11.crossattention.output.dense.weight', 'bert.encoder.layer.11.crossattention.output.LayerNorm.weight', 'bert.encoder.layer.5.crossattention.output.LayerNorm.bias', 'bert.encoder.layer.8.crossattention.output.LayerNorm.weight', 'bert.encoder.layer.6.crossattention.output.LayerNorm.weight', 'bert.encoder.layer.7.crossattention.self.query.bias', 'bert.encoder.layer.10.crossattention.output.LayerNorm.bias', 'bert.encoder.layer.8.crossattention.output.dense.weight', 'bert.encoder.layer.1.crossattention.self.value.weight', 'bert.encoder.layer.10.crossattention.self.query.weight', 'bert.encoder.layer.5.crossattention.output.LayerNorm.weight', 'bert.encoder.layer.5.crossattention.self.query.bias', 'bert.encoder.layer.8.crossattention.self.query.bias', 'bert.encoder.layer.7.crossattention.self.query.weight', 'bert.encoder.layer.1.crossattention.output.dense.weight']
bert2bert_new_initialized_weights = ['decoder.' + BertLMHeadModel_new_initialized_weights[i] for i in range(len(BertLMHeadModel_new_initialized_weights))]
# print(bert2bert_new_initialized_weights)

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.decoder.weight', 'cls.predictions.bias', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.weight', 'cls.seq_relationship.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertLMHeadModel: ['cls.seq_relationship.weight', 'cls.seq_relatio

In [ ]:
# encoder = BertModel.from_pretrained("bert-base-uncased") # config=encoder_config
# decoder = BertForMaskedLM.from_pretrained("bert-base-uncased") #config=decoder_config
# model = EncoderDecoderModel(encoder=encoder, decoder=decoder)

In [4]:
import copy 
new_bert2bert = copy.deepcopy(bert2bert)
# old_bert2bert = copy.deepcopy(bert2bert)

In [5]:
# print(new_bert2bert.decoder.bert.encoder.layer)
NUM_LAYER_DECODER = 4
new_bert2bert.decoder.bert.encoder.layer = new_bert2bert.decoder.bert.encoder.layer[:NUM_LAYER_DECODER]

In [6]:
# print(new_bert2bert.decoder.bert.encoder.layer)
bert2bert = new_bert2bert

In [3]:
'''
def count_parameters(model):
    # table = PrettyTable(["Modules", "Parameters"])
    table = {}
    total_params = 0
    for name, parameter in model.named_parameters():
        if not parameter.requires_grad: continue
        params = parameter.numel()
        table[name] = params
        total_params+=params
    # print(table)
    
    print(f"Total Trainable Params: {total_params}")
    return total_params, table
    
# total_params, table = count_parameters(model)
# print(total_params)
# for k, v in table.items():
#     print(k, v)
    
total_params, table = count_parameters(bert2bert)
print(total_params)
for k, v in table.items():
    print(k, v)
'''

Total Trainable Params: 247363386
247363386
encoder.embeddings.word_embeddings.weight 23440896
encoder.embeddings.position_embeddings.weight 393216
encoder.embeddings.token_type_embeddings.weight 1536
encoder.embeddings.LayerNorm.weight 768
encoder.embeddings.LayerNorm.bias 768
encoder.encoder.layer.0.attention.self.query.weight 589824
encoder.encoder.layer.0.attention.self.query.bias 768
encoder.encoder.layer.0.attention.self.key.weight 589824
encoder.encoder.layer.0.attention.self.key.bias 768
encoder.encoder.layer.0.attention.self.value.weight 589824
encoder.encoder.layer.0.attention.self.value.bias 768
encoder.encoder.layer.0.attention.output.dense.weight 589824
encoder.encoder.layer.0.attention.output.dense.bias 768
encoder.encoder.layer.0.attention.output.LayerNorm.weight 768
encoder.encoder.layer.0.attention.output.LayerNorm.bias 768
encoder.encoder.layer.0.intermediate.dense.weight 2359296
encoder.encoder.layer.0.intermediate.dense.bias 3072
encoder.encoder.layer.0.output.dense

In [6]:
# print(bert2bert_new_initialized_weights)
'decoder.bert.encoder.layer.11.output.LayerNorm.bias'[8:]
'decoder.bert.encoder.layer.11.output.LayerNorm.bias'[:7] ==

'decoder'

In [4]:
for name, param in bert2bert.named_parameters():
    print(name)

encoder.embeddings.word_embeddings.weight
encoder.embeddings.position_embeddings.weight
encoder.embeddings.token_type_embeddings.weight
encoder.embeddings.LayerNorm.weight
encoder.embeddings.LayerNorm.bias
encoder.encoder.layer.0.attention.self.query.weight
encoder.encoder.layer.0.attention.self.query.bias
encoder.encoder.layer.0.attention.self.key.weight
encoder.encoder.layer.0.attention.self.key.bias
encoder.encoder.layer.0.attention.self.value.weight
encoder.encoder.layer.0.attention.self.value.bias
encoder.encoder.layer.0.attention.output.dense.weight
encoder.encoder.layer.0.attention.output.dense.bias
encoder.encoder.layer.0.attention.output.LayerNorm.weight
encoder.encoder.layer.0.attention.output.LayerNorm.bias
encoder.encoder.layer.0.intermediate.dense.weight
encoder.encoder.layer.0.intermediate.dense.bias
encoder.encoder.layer.0.output.dense.weight
encoder.encoder.layer.0.output.dense.bias
encoder.encoder.layer.0.output.LayerNorm.weight
encoder.encoder.layer.0.output.LayerNorm

In [7]:
# freeze the whole decoder model
require_grad_count = 0

for name, param in bert2bert.named_parameters():
    # if name in bert2bert_new_initialized_weights or name[:11] == 'decoder.cls':
    if name[:7] == 'decoder':  
        # print(name , ' NOT freeze')
        param.requires_grad = True
        require_grad_count += 1
    else:
        # print('freezing top layers ', name)
        param.requires_grad = False
        
# check model architecture
print(f'these parameters require grad: {require_grad_count} layers ')
for name, param in bert2bert.named_parameters():
    if param.requires_grad:
        print(name)

these parameters require grad: 114 layers 
decoder.bert.embeddings.word_embeddings.weight
decoder.bert.embeddings.position_embeddings.weight
decoder.bert.embeddings.token_type_embeddings.weight
decoder.bert.embeddings.LayerNorm.weight
decoder.bert.embeddings.LayerNorm.bias
decoder.bert.encoder.layer.0.attention.self.query.weight
decoder.bert.encoder.layer.0.attention.self.query.bias
decoder.bert.encoder.layer.0.attention.self.key.weight
decoder.bert.encoder.layer.0.attention.self.key.bias
decoder.bert.encoder.layer.0.attention.self.value.weight
decoder.bert.encoder.layer.0.attention.self.value.bias
decoder.bert.encoder.layer.0.attention.output.dense.weight
decoder.bert.encoder.layer.0.attention.output.dense.bias
decoder.bert.encoder.layer.0.attention.output.LayerNorm.weight
decoder.bert.encoder.layer.0.attention.output.LayerNorm.bias
decoder.bert.encoder.layer.0.crossattention.self.query.weight
decoder.bert.encoder.layer.0.crossattention.self.query.bias
decoder.bert.encoder.layer.0.cro

In [8]:
# %reset
import data # data.py from local directory
# from data import *
from data import batch2BertPadId, createAttMask, collate_fn, SummarisationDataset

1.11.0
clss tensor([[  0,  21,  38,  56,  83,  96, 134, 159, 170, 186, 195, 238, 253, 286,
         309, 340, 350, 374, 390, 407, 422,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
          -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
          -1,  -1,  -1],
        [  0,  24,  57,  91, 110, 126, 150, 164, 179, 192, 204, 215, 229, 254,
         266, 295, 314, 341, 371, 387, 407, 428, 451,  -1,  -1,  -1,  -1,  -1,
          -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
          -1,  -1,  -1],
        [  0,  19,  39,  60,  88, 109, 126, 155, 174, 186, 201, 224, 257, 266,
         290, 332, 352, 366, 388, 397, 420, 441, 456, 492, 524, 543, 564, 580,
         590, 609, 627, 644, 664, 685, 701, 728, 750, 772, 781, 795, 816, 841,
         855, 864, 880]])
token_len_src tensor([435, 469, 512])
token_len_tgt tensor([ 40, 100,  50])
sent_len tensor([21, 23, 45])
padding_token tensor([-1, -1, -1])
segs tensor([[ 0,  0,  0,  ..., -1, -1, -1],
        [ 0,  0

In [9]:
# test dataset class
train_file = './preprocessed/train_data.hdf5'
test_file = './preprocessed/test_data.hdf5'
valid_file ='./preprocessed/valid_data.hdf5'
enc_maxlength = 512
dec_maxlength = 512

train_dataset = SummarisationDataset(path = train_file)
print('train_dataset length = ', len(train_dataset))

print(train_dataset[0].keys())
# print(bert_dataset[0]['src'])
print(train_dataset[0]['token_len_src'])

batch_list = [train_dataset[idx] for idx in range(3)]
print(len(batch_list))
# print(batch_list)

train_dataset length =  287083
dict_keys(['clss', 'token_len_src', 'token_len_tgt', 'sent_len', 'padding_token', 'segs', 'src', 'src_sent_labels', 'tgt'])
435
3


In [11]:
import random

test_dataset = SummarisationDataset(test_file)
valid_dataset = SummarisationDataset(valid_file)

idx = random.randint(0,len(train_dataset)-1 )
print(idx)
aa_train = train_dataset.__getitem__(idx)
print(aa_train['src'][:6])

print(test_dataset.__getitem__(random.randint(0,len(test_dataset)-1 )) ['src'][:6])
print(valid_dataset.__getitem__(random.randint(0,len(valid_dataset)-1 )) ['src'][:6])


bb = train_dataset.__getitem__(100)
print(bb['src'][:6])

print(test_dataset.__getitem__(10) ['src'][:6])
print(valid_dataset.__getitem__(10) ['src'][:6])

198933
[  101  2410 29627  8889  9765  1010]
[  101  1037  2388  5496  1997 15488]
[  101  1037  2088  2162  1045 29624]
[ 101 2044 2108 7376 2013 2014]
[  101  1006 13229  1007  1999  2014]
[ 101 2044 2093 2706 1997 8503]


In [6]:
train_dataset = SummarisationDataset(path = train_file)
batch_list = [train_dataset[idx] for idx in range(3)]
batch = collate_fn(batch_list)

for k, v in batch.items():
    print(k, v)

torch.Size([3, 512])
clss tensor([[   0,   40,   66,  105,  142,  171,  212,  239,  251,  273,  288,  350,
          388,  413,  426,  456,  506,  549,  569,  593,  612,  621,  644,  690,
          721,  751,  793,  810,  841,  870,  900,  915,  947,  981, 1012, 1068,
         1055, 1097, 1116, 1142, 1165, 1211, 1243, 1266, 1297, 1339, 1396, 1412,
         1424, 1437, 1475, 1514, 1548, 1592, 1604, 1627, 1516, 1548, 1568, 1582,
         1485, 1511, 1534, 1559, 1582, 1619, 1642, 1663, 1685, 1701, 1711, 1722,
         1745, 1758, 1792, 1813, 1854, 1893, 1920, 1947, 1976, 2001, 2020, 2049,
         2090, 2116, 2126, 2149, 2182, 2217, 2253, 2273, 2284, 2321, 1607, 1620,
         1637, 1655, 1665, 1674],
        [   0,   48,   86,  146,  177,  189,  218,  247,  291,  356,  377,  405,
          443,  466,  496,  518,  554,  576,  608,  653,  690,  703,  716,  755,
          778,  858,  904,  933,  949,  941,  991, 1017, 1051, 1069, 1091, 1119,
         1138,  744,  754,  763,  780,  801,  811

In [11]:
BATCH_SIZE = 8
train_dataset = SummarisationDataset(train_file)
test_dataset = SummarisationDataset(test_file)
valid_dataset = SummarisationDataset(valid_file)

train_dataloader = DataLoader(train_dataset, 
                          batch_size=BATCH_SIZE, 
                          collate_fn = collate_fn,
                          num_workers = 8, shuffle=True)

test_dataloader = DataLoader(test_dataset, 
                          batch_size=BATCH_SIZE, 
                          collate_fn = collate_fn,
                          num_workers = 8, shuffle=True)

valid_dataloader = DataLoader(valid_dataset, 
                          batch_size=BATCH_SIZE, 
                          collate_fn = collate_fn,
                          num_workers = 8, shuffle=True)

valid_batch1 = next(iter(valid_dataloader))
print(type(valid_batch1['tgt']))
print(valid_batch1.keys())
print(valid_batch1['src'].shape)
print(valid_batch1['src'])


<class 'torch.Tensor'>
dict_keys(['clss', 'token_len_src', 'token_len_tgt', 'sent_len', 'padding_token', 'segs', 'src', 'src_sent_labels', 'tgt'])
torch.Size([8, 512])
tensor([[  101,  1037,  2158,  ...,  2056,  1012,   102],
        [  101,  2750,  1037,  ...,  2030,  2178,  2364],
        [  101,  1037,  2136,  ...,  1010,  1996,  2317],
        ...,
        [  101,  1037,  3232,  ..., 10710,  7279, 29431],
        [  101,  1037,  5776,  ..., 29623, 19841,  2620],
        [  101,  2047,  2259,  ...,  2196,  2042,  2062]])


In [21]:
# convert -1 to pad_token_id of bert tokenizer

tgt1 = batch2BertPadId(train_batch1['tgt'])
mask_tgt1 = createAttMask(train_batch1['tgt'])

print(tgt1[0,:])
print(mask_tgt1[0,:])

print(sum(tgt1[0,:] == 0), sum(mask_tgt1[0,:] == 0))

tensor([1.0000e+00, 2.8590e+03, 2.7785e+04, 2.3310e+03, 9.5650e+03, 9.4660e+03,
        2.0000e+03, 6.4860e+03, 1.0100e+03, 2.1100e+03, 2.8650e+03, 4.3110e+03,
        3.0000e+00, 1.9960e+03, 2.4170e+03, 2.8920e+03, 2.5540e+03, 1.9970e+03,
        2.8590e+03, 2.0030e+03, 6.0160e+03, 1.7732e+04, 1.9980e+03, 6.0670e+03,
        3.0000e+00, 5.6060e+03, 2.9880e+03, 5.2290e+03, 2.4080e+03, 1.0370e+03,
        2.1930e+03, 1.9970e+03, 5.7210e+03, 3.0000e+00, 1.0069e+04, 5.3430e+03,
        4.0730e+03, 2.0890e+03, 2.0220e+03, 2.2532e+04, 2.0110e+03, 3.5220e+03,
        3.0820e+03, 4.5420e+03, 1.0100e+03, 2.0620e+03, 1.9939e+04, 2.0000e+00,
        2.8410e+03, 3.0000e+00, 3.3090e+03, 1.0050e+03, 6.6330e+03, 1.7180e+04,
        2.0150e+03, 1.0050e+03, 7.3880e+03, 7.9590e+03, 1.7819e+04, 2.0210e+03,
        1.1186e+04, 1.0360e+03, 1.9258e+04, 1.0050e+03, 2.8750e+03, 6.3680e+03,
        3.0000e+00, 2.8660e+03, 1.1514e+04, 3.0030e+03, 1.2829e+04, 2.5210e+03,
        4.2700e+03, 2.1010e+03, 4.0810e+

In [17]:
import os
os.environ['TRANSFORMERS_OFFLINE'] = 'yes'

In [18]:
from transformers import BertTokenizer
tz = BertTokenizer.from_pretrained("bert-base-uncased")

In [10]:
print(tz.decode(tgt1[0,:256]))
print(tz.decode(tgt1[1,:256]))

print(tz.decode(train_batch1['tgt'][0,:]))

NameError: name 'tgt1' is not defined

In [12]:
# train loop
# pad_id = 0
optimizer = torch.optim.Adam(bert2bert.parameters(), lr=0.0001)
loss_fct = nn.CrossEntropyLoss(ignore_index = -100)
criterion = nn.NLLLoss(ignore_index = -100)
bert2bert = bert2bert.to(device)

In [103]:
bert2bert.config.decoder.vocab_size

30522

In [62]:
'''
def compute_loss(prediction_scores, labels):
    """Compute our custom loss"""
    shifted_prediction_scores = prediction_scores[:, :-1, :].contiguous() # prediction_scores is logits
    labels = labels[:, 1:].contiguous()
    loss_fct = nn.CrossEntropyLoss(ignore_index = -100)
    lm_loss = loss_fct(shifted_prediction_scores.view(-1, bert2bert.config.decoder.vocab_size), 
                       labels.view(-1))

    return lm_loss

def compute_loss2(prediction_scores, labels):
    """Compute our custom loss"""
    predictions = F.softmax(prediction_scores)
    predictions = predictions[:, :-1, :].contiguous()
    labels = labels[:, 1:]

    rearranged_output = predictions.view(predictions.shape[0]*predictions.shape[1], -1)
    rearranged_target = labels.contiguous().view(-1)

    lm_loss = criterion(rearranged_output, rearranged_target)

    return lm_loss
    
'''

In [13]:
# one train loop

def train_model():
    bert2bert.train()
    epoch_loss = 0

    for i, batch in enumerate(tqdm(train_dataloader)):
        optimizer.zero_grad()
        src, tgt = batch['src'], batch['tgt'] # 

        # convert -1 to 0
        src, tgt = batch2BertPadId(src), batch2BertPadId(tgt) # .type(LongTensor)

        # create label
        labels = tgt.clone()
        labels[labels == 0] = -100 # by default loss function ignore id = -100

        # create mask
        src_att_mask = createAttMask(src)
        tgt_att_mask = createAttMask(tgt)

        src, tgt, labels = src.to(device), tgt.to(device), labels.to(device)
        src_att_mask, tgt_att_mask = src_att_mask.to(device), tgt_att_mask.to(device)

        out = bert2bert(input_ids=src, attention_mask=src_att_mask,
                        decoder_input_ids=tgt, decoder_attention_mask=tgt_att_mask,
                        labels=labels)
        loss, prediction_scores = out.loss, out.logits

        loss.backward()
        torch.nn.utils.clip_grad_norm_(bert2bert.parameters(), 1.0)
        optimizer.step()
        epoch_loss += loss.item()

    print("Mean training epoch loss:", (epoch_loss / len(train_dataloader)))

In [16]:
def eval_model():
    bert2bert.eval()
    epoch_loss = 0

    for i, batch in enumerate(tqdm(valid_dataloader)):
        optimizer.zero_grad()
        
        src, tgt = batch['src'], batch['tgt'] # 
        # convert -1 to 0
        src, tgt = batch2BertPadId(src), batch2BertPadId(tgt) # .type(LongTensor)
        # create label
        labels = tgt.clone()
        labels[labels == 0] = -100 # by default loss function ignore id = -100
        # create mask
        src_att_mask = createAttMask(src)
        tgt_att_mask = createAttMask(tgt)

        src, tgt, labels = src.to(device), tgt.to(device), labels.to(device)
        src_att_mask, tgt_att_mask = src_att_mask.to(device), tgt_att_mask.to(device)

        out = bert2bert(input_ids=src, attention_mask=src_att_mask,
                        decoder_input_ids=tgt, decoder_attention_mask=tgt_att_mask,
                        labels=labels)
        loss, prediction_scores = out.loss, out.logits

        epoch_loss += loss.item()
    print("Mean validation epoch loss:", (epoch_loss / len(valid_dataloader)))


In [17]:
# main training loop
# MAIN TRAINING LOOP
NUM_EPOCHS = 6
save_location = './models/'
model_name = 'bert2bert.pt'

for epoch in range(NUM_EPOCHS):
    print("Starting epoch", epoch+1)
    train_model()
    eval_model()

print("Saving model ..")
if not os.path.exists(save_location):
    os.makedirs(save_location)
save_location = os.path.join(save_location, model_name)
torch.save(bert2bert, save_location)

Starting epoch 1


100%|███████████████████████████| 35886/35886 [58:12<00:00, 10.28it/s]


Mean training epoch loss: 2.7072609502728526


100%|███████| 1671/1671 [01:48<00:00, 15.38it/s]


Mean validation epoch loss: 2.561582028402104
Starting epoch 5


100%|█████| 35886/35886 [58:09<00:00, 10.28it/s]


Mean training epoch loss: 2.6317593583041248


100%|███████| 1671/1671 [01:48<00:00, 15.46it/s]


Mean validation epoch loss: 2.5293476005858966
Starting epoch 6


100%|█████| 35886/35886 [58:14<00:00, 10.27it/s]


Mean training epoch loss: 2.5729181375224766


100%|███████| 1671/1671 [01:48<00:00, 15.39it/s]

Mean validation epoch loss: 2.5062586908779907
Saving model ..


NameError: name 'os' is not defined

In [19]:
print("Saving model ..")
if not os.path.exists(save_location):
    os.makedirs(save_location)
save_location = os.path.join(save_location, model_name)
torch.save(bert2bert, save_location)

Saving model ..


In [20]:
bert2bert_checkpoint = { 
    'epoch': epoch,
    'model': bert2bert.state_dict(),
    'optimizer': optimizer.state_dict()
}

torch.save(bert2bert_checkpoint, './models/bert2bert_checkpoint.pt')


In [28]:
eval_model()

100%|█████████████████████████████| 1671/1671 [01:46<00:00, 15.70it/s]

Mean validation loss: 3.9672808475939547


In [80]:
batch = next(iter(train_dataloader))

In [23]:
print(batch.keys())
torch.cuda.empty_cache()

dict_keys(['clss', 'token_len_src', 'token_len_tgt', 'sent_len', 'padding_token', 'segs', 'src', 'src_sent_labels', 'tgt'])


In [83]:
bert2bert.train()
optimizer.zero_grad()

epoch_loss = 0

src, tgt = batch['src'], batch['tgt'] # 

# convert -1 to 0
src, tgt = batch2BertPadId(src), batch2BertPadId(tgt) # .type(LongTensor)
# create label
labels = tgt.clone()
labels[labels == 0] = -100

# print('tgt = ', tgt)
# print('label = ', labels)

# create mask
src_att_mask = createAttMask(src)
tgt_att_mask = createAttMask(tgt)

src, tgt, labels = src.to(device), tgt.to(device), labels.to(device)
src_att_mask, tgt_att_mask = src_att_mask.to(device), tgt_att_mask.to(device)

out = bert2bert(input_ids=src, attention_mask=src_att_mask,
                decoder_input_ids=tgt, decoder_attention_mask=tgt_att_mask,
                labels=labels)

loss = out[0]
prediction_scores = out[1]

loss.backward()
torch.nn.utils.clip_grad_norm_(bert2bert.parameters(), 1.0)
optimizer.step()

epoch_loss += loss.item()

print(epoch_loss)

8.511220932006836


In [72]:
out[0]

tensor(8.6513, device='cuda:0', grad_fn=<NllLossBackward0>)

In [65]:
loss, logits = out.loss, out.logits
print(logits.shape)
print(loss)
print(epoch_loss)
print(loss2)

print(tgt.shape)
print(prediction_scores.shape)

torch.Size([8, 75, 30522])
tensor(9.9302, device='cuda:0', grad_fn=<NllLossBackward0>)
-0.10400070995092392
tensor(-0.1040, device='cuda:0', grad_fn=<NllLossBackward0>)
torch.Size([8, 75])
torch.Size([8, 75, 30522])


In [66]:

loss, logits = out.loss, out.logits
print(logits.shape)
print(loss)

loss.backward()
torch.nn.utils.clip_grad_norm_(bert2bert.parameters(), 1.0)
optimizer.step()

epoch_loss += loss.item()

print(epoch_loss)

torch.Size([8, 75, 30522])
tensor(9.9302, device='cuda:0', grad_fn=<NllLossBackward0>)


RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.